apiVersion: v1
kind: Service
metadata:
  name: everybucket-service
spec:
  selector:
    app: node-everybucket
  ports:
  - name: http
    protocol: TCP
    port: 5001
    targetPort: 5001
  type: LoadBalancer